// FETCH
export const FETCH_ALL_DATA_REQUEST = 'FETCH_ALL_DATA_REQUEST';
export const FETCH_ALL_DATA_SUCCESS = 'FETCH_FETCH_ALL_DATA_SUCCES';
export const FETCH_ALL_DATA_SUCCESS_EX = 'FETCH_FETCH_ALL_DATA_SUCCES_EX';
export const FETCH_ALL_DATA_SUCCESS_CARD = 'FETCH_ALL_DATA_SUCCESS_CARD';
export const FETCH_ALL_DATA_SUCCESS_CITIES = 'FETCH_ALL_DATA_SUCCESS_CITIES';
export const FETCH_ALL_DATA_FAIL = 'FETCH_FETCH_ALL_DATA_FAIL';

//LOG
export const USER_LOGGED_SUCCESS = 'USER_LOGGED_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';


// CART 
export const ADD_TO_CART = 'ADD_TO_CART';
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';
export const REMOVE_TO_CART = 'REMOVE_TO_CART';
