export const FETCH_ALL_DATA_REQUEST = 'FETCH_ALL_DATA_REQUEST';
export const FETCH_ALL_DATA_SUCCESS = 'FETCH_FETCH_ALL_DATA_SUCCES';
export const FETCH_ALL_DATA_SUCCESS_EX = 'FETCH_FETCH_ALL_DATA_SUCCES_EX';
export const FETCH_ALL_DATA_SUCCESS_CARD = 'FETCH_ALL_DATA_SUCCESS_CARD';
export const FETCH_ALL_DATA_SUCCESS_CITIES = 'FETCH_ALL_DATA_SUCCESS_CITIES';
export const FETCH_ALL_DATA_FAIL = 'FETCH_FETCH_ALL_DATA_FAIL';
export const USER_LOGGED_SUCCESS = 'USER_LOGGED_SUCCESS';
export const ADD_TO_CART = 'ADD_TO_CART';
