export const FETCH_ALL_DATA_REQUEST = 'FETCH_ALL_DATA_REQUEST';
export const FETCH_ALL_DATA_SUCCESS = 'FETCH_FETCH_ALL_DATA_SUCCES';
export const FETCH_ALL_DATA_SUCCESS_EX = 'FETCH_FETCH_ALL_DATA_SUCCES_EX';
export const FETCH_ALL_DATA_FAIL = 'FETCH_FETCH_ALL_DATA_FAIL';
